// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "250c4a10-0086-4247-a606-38553ad49062");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 608);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e753dc33-45e2-4129-b0cb-b005dccae098}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1570604587103");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1570608187103");
user_pref("browser.search.region", "PL");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1570604626");
user_pref("browser.slowStartup.averageTime", 1010);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.lastColdStartupCheck", 1570604626);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1570604585817");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "5e7dfa7e89ad4469b29d9fc0d6811225");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191001234643");
user_pref("extensions.lastAppVersion", "69.0.2");
user_pref("extensions.lastPlatformVersion", "69.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"220542bc-6e5f-4e91-aa21-97f2320ce203\",\"fxmonitor@mozilla.org\":\"dfaf9981-aaf6-4c1b-b321-dfa48dbb7e50\",\"screenshots@mozilla.org\":\"f0120349-03ac-463f-a32c-45ca2095f1d2\",\"webcompat-reporter@mozilla.org\":\"f6ae76b0-f56e-4015-a377-2a1d3824f5a0\",\"webcompat@mozilla.org\":\"fbd818fe-256d-4d4e-906e-f090a6671a43\",\"default-theme@mozilla.org\":\"3ae32af1-296e-47d2-93df-286d2780bdbc\"}");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "69.0.2");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x5917");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "25.20.100.6519");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x5917");
user_pref("sanity-test.driver-version", "25.20.100.6519");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20191001234643");
user_pref("security.sandbox.content.tempDirSuffix", "{1cdd83d8-f297-4f41-a18e-57a47d3b1fd2}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{73d5c19b-cc66-4401-8725-dd7279e48941}");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1570604624);
user_pref("toolkit.telemetry.cachedClientID", "9b189157-89bd-4b46-8db6-e44730655a71");
user_pref("toolkit.telemetry.previousBuildID", "20191001234643");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
